### ISSUE TITLE
Temperature changed only temporarily

### ISSUE THREAD

**Issue by michalesn** [luc-ass/homebridge-evohome#65] opened 2020-12-23 15:19 UTC
Using hoobs bridge, integrated into IOS home app, when changing temperature on any evohome thermostat, the temperature is changed only temporarily (although the previous temperature was set as permanent). It basically create some time schedule, which cannot be changed or viewed anywhere in the hoobs nor home app, only in the original Honeywell home app. Thanx

**Comment by dongilles** [comment] 2020-12-27 10:02
I have Homebridge running and I have the same problem. hopefully someone knows what the problem is

**Comment by luc-ass** [comment] 2021-01-14 08:41
This plugin asks the Honeywell server for the next switchPoint and sets the temperature until that time. If there are no setPoints ti will change the temperature until 00:00 h the next day. This part of homebridge-evohome needs love, so if you can contribute, your help is more than welcome!

**Comment by luc-ass** [comment] 2021-01-17 10:45
Okay, to further elaborate on this: When this plugin was first written, the endDate was set to a specific duration after changing the temperature (for example 20 mins). To improve on this, it was then advanced to changing the temperature until the next programed endDate. This behavior was introduced to prevent the system from staying on all the time. What would be your expected behavior for the following use cases:
1) Your room has defined switching times and you change the temperature from Siri/Home.app
2) Your room does not have defined switching times and you change the temperature from Siri/Home.app

**Comment by luc-ass** [comment] 2021-01-20 14:27
This should be fixed as of #72 
Check out version 0.8.0 or above
Feel free to reopen this if your problems persist

**Closed by luc-ass** 2021-01-20 14:27 UTC
Labels: help wanted, more information needed
